spring:
    application:
        name: auth-service
    profiles:
        active: development
        
---

server:
    port: 9100
    
spring:
    profiles: development
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/core_ui_security
        username: core_ui_security
        password: core_ui_security
        initialization-mode: never
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

security:
    jwt:
        uri: /auth/**
        passwordRecoveryUri: /passwordRecovery/**
        header: Authorization
        prefix: Bearer 
        expiration: 1800
        secret: JwtSecretKey

logging:
    file: /logs/genesis-jwt-auth.log
---

server:
    port: 9100
    
spring:
    profiles: stage
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/core_ui_security
        username: core_ui_security
        password: core_ui_security
        initialization-mode: never
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

security:
    jwt:
        uri: /auth/**
        passwordRecoveryUri: /passwordRecovery/**
        header: Authorization
        prefix: Bearer 
        expiration: 1800
        secret: JwtSecretKey

logging:
    file: /logs/genesis-jwt-auth.log

---

server:
    port: 9100
    
spring:
    profiles: production
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/core_ui_security
        username: core_ui_security
        password: core_ui_security
        initialization-mode: never
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

security:
    jwt:
        uri: /auth/**
        passwordRecoveryUri: /passwordRecovery/**
        header: Authorization
        prefix: Bearer 
        expiration: 1800
        secret: JwtSecretKey
        
logging:
    file: /logs/genesis-jwt-auth.log