spring:
    application:
        name: api-service
    profiles:
        active: development
        
---

server:
    port: 9300
    
spring:
    profiles: development    
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://temporal-migracion.cdssut7oieqx.us-east-1.rds.amazonaws.com:3306/magus_stage
        #username: magus
        #password: Magu!20i7
        url: jdbc:mysql://rdsharris.cdssut7oieqx.us-east-1.rds.amazonaws.com:3306/magus
        username: magus
        password: Magu!20i7
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

logging:
    file: /logs/genesis-api-service.log

---

server:
    port: 9300
    
spring:
    profiles: stage    
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rdsharris.cdssut7oieqx.us-east-1.rds.amazonaws.com:3306/magus
        username: magus
        password: Magu!20i7
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

logging:
    file: /logs/genesis-api-service.log

---

server:
    port: 9300
    
spring:
    profiles: production    
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rdsharris.cdssut7oieqx.us-east-1.rds.amazonaws.com:3306/magus
        username: magus
        password: Magu!20i7
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
    
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            
debug: true

logging:
    file: /logs/genesis-api-service.log