# Give a name to the eureka server
spring:
    application:
        name: eureka-server
    profiles:
        active: development
       
---        

spring:
    profiles: development

# default port for eureka server
server:
    port: 8761
    
# eureka by default will register itself as a client. So, we need to set it to false.
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
       
logging:
    file: /logs/genesis-eureka-server.log
---        

spring:
    profiles: stage

# default port for eureka server
server:
    port: 8761
    
# eureka by default will register itself as a client. So, we need to set it to false.
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        
logging:
    file: /logs/genesis-eureka-server.log

---

spring:
    profiles: production

# default port for eureka server
server:
    port: 8761
    
# eureka by default will register itself as a client. So, we need to set it to false.
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        
logging:
    file: /logs/genesis-eureka-server.log